services:
  - type: web
    name: tds-mcp
    runtime: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app:app